### ISSUE TITLE
Добавить информацию о бизнес-логике

### ISSUE THREAD

**Issue by AleksanderNekr** [TeamHSE/study-platform#11]
Добавить поля к сущностям и методы (действия, ими выполняемые) в [вики](https://github.com/TeamHSE/study-platform/wiki/Business-model)

**Comment by disk0Dancer** [comment]
https://github.com/TeamHSE/study-platform/wiki/Business-model#роли-пользователей-на-платформе

**Comment by disk0Dancer** [comment]
https://github.com/TeamHSE/study-platform/wiki/Business-model#описание-сущностей

**Comment by AleksanderNekr** [comment]
Пока пойдет, по ходу лучше разберемся на более низком уровне
