### ISSUE TITLE
Обновить docker-compose

### ISSUE THREAD

**Issue by AleksanderNekr** [TeamHSE/study-platform#27]
После добавления ORM и БД нужно добавить ее в docker-compose

**Comment by AleksanderNekr** [comment]
@disk0Dancer для задачи создал ветку feat/compose-db, плиз отправь коммиты в нее, а потом пулл реквест из нее в develop

**Comment by disk0Dancer** [comment]
Ахах, ух блин, я уже в свою ветку локальную сделал, типо "орм под ключ". Я перекину комиты в отдельную тогда..

**Comment by AleksanderNekr** [comment]
> Ахах, ух блин, я уже в свою ветку локальную сделал, типо "орм под ключ". Я перекину комиты в отдельную тогда..

Да не, оставь как есть, лишние телодвижения
