### ISSUE TITLE
Сменить концепцию проекта

### ISSUE THREAD

**Issue by AleksanderNekr** [TeamHSE/study-platform#40]
https://github.com/TeamHSE/study-platform/blob/08596849a2fb6b51d945ac20067d0549498d8234/backend/src/entity/User.ts#L31-L40

@disk0Dancer, @ZakharMolchanov, а зачем у юзера поля weight, height, achievements: string, healthIssues: string; ?

**Comment by disk0Dancer** [comment]
Привет! По бизнес логике, я задумывал приложение как платформу для персональных тренировок, поэтому поля описывают особенности здоровья человека, в перспективе, это важно для тренеров, чтобы адаптировать программу.

Контроль весе на уровне фичи, можно прикручивать динамику изменений и ставить цели.

**Comment by AleksanderNekr** [comment]
> Привет! По бизнес логике, я задумывал приложение как платформу для персональных тренировок, поэтому поля описывают особенности здоровья человека, в перспективе, это важно для тренеров, чтобы адаптировать программу.
> 
> Контроль весе на уровне фичи, можно прикручивать динамику изменений и ставить цели.

Для тренировок?)) Я думал, мы обучающую платформу делаем) Или мы когда-то успели концепцию сменить?

**Comment by AleksanderNekr** [comment]
Глянул в вики описание сущностей, похоже все-таки тренировок)) Как вовремя я это осознал...
