### ISSUE TITLE
Проектирование эндпоинтов пользователей

### ISSUE THREAD

**Issue by AleksanderNekr** [TeamHSE/study-platform#8]
Роли юзеров	
			
	Админ	Служебная роль, можно все	
	супер юзер			
		Процессы 		
				
		Фичи		
			просмотр пользователей, доступ к просмотру содержимого всех курсов	
				
				
				
				
				
				
	Модератор	Описание	Служебная роль, при публикации курса, внесении изменений задействуется проверка контента	
				
		Процессы 		
			рецензия изменений в курсе	
			принять/отказать в изменениях + комментарий	
		Фичи		
			журнал заявок  на изменения	
				
				
				
				
				
				
				
				
				
	Пользователь	Описание	посетитель сайте, пришел за программой тренировок	
				
		Процессы 		
			регистрация	
			просмотр курсов	
			запись на курсы	
			отметка выполнения шага курса	
			просмотр рейтинга	
				
		Фичи		
			профиль	
				
	Тренер	описание	автор курса	(хз, выделить отдельно или просто дать доступ к функциям 
				
				
		процессы	управление структурой курса	
			управление шагами в курсе	
			управление модулями в курсе	
				
			управление подписчиками курса	
			чат с подписчиками?

**Comment by AleksanderNekr** [comment]
@disk0Dancer, чекни эндпоинты, как по БЛ соотносятся

**Comment by disk0Dancer** [comment]
Думаю, что нужно добавить полей и показать связь с курсами, поля взять из схемы бд.

Связь с курсами:
{
 ....
 Courses: {
  Contributor:{
   Link.course1
   ...
  },
  Viewer:
  {
   Link.course2
  }
 }
}

**Comment by AleksanderNekr** [comment]
@AleksanderNekr 
Информацию о курсах (организаторах, слушателях), как договрились, сделаем в группе эндпоинтов курсов

**Comment by AleksanderNekr** [comment]
В таком случае есть что-то еще, что добавить/убрать из эндпоинтов?
