### ISSUE TITLE
Проектирование базы данных

### ISSUE THREAD

**Issue by disk0Dancer** [TeamHSE/study-platform#9]

**Comment by disk0Dancer** [comment]
![Image](https://github.com/TeamHSE/study-platform/assets/89835485/cecee9d0-6688-4322-8193-bc3ad1247433)

**Comment by AleksanderNekr** [comment]
@disk0Dancer 
Что значит отношение 1 courses_viewers к N users: 1 участник курса связан с несколькими пользователями?

**Comment by AleksanderNekr** [comment]
Пойдет)
